# V104 매출처별 세금계산서 합계표
title = "VAT104"
[V104]
# 매출처별 세금계산서 합계표의 화면을 위한 테이블 정의
# 화면을 구성하게되는 입력폼이나 출력되는 대상을 정하는 것과 동일합니다.
schema = [
    ["VATKEY","String","true"],             #Main Key. << 모든 정의에 들어 있어야 함. 세번째 항목은 Key 값 유무.
    ["COMPANY_CODE","String"],       #회사코드
    ["YEAR","String"],               #년도
    ["VATQT","String"],              #신고분기
    ["VATRPTTYPE","String"],         #신고타입

    ["TOTAL_SALES_CNT","Number"],             #매출세금계산서 총합계-매출처수 합계
    ["TOTAL_SALES_QTY","Number"],             #매출세금계산서 총합계-매수 합계
    ["TOTAL_SALES_ACT_AMT","Number"],         #매출세금계산서 총합계-공급가액 합계
    ["TOTAL_SALES_TAX_AMT","Number"],         #매출세금계산서 총합계-세액 합계

    ["ELEC_BUS_SALES_CNT","Number"],          #매출세금계산서 총합계-전자세금계산서발급분-사업자등록번호 발급분-매출처수
    ["ELEC_BUS_SALES_QTY","Number"],          #매출세금계산서 총합계-전자세금계산서발급분-사업자등록번호 발급분-매수
    ["ELEC_BUS_SALES_ACT_AMT","Number"],      #매출세금계산서 총합계-전자세금계산서발급분-사업자등록번호 발급분-공급가액
    ["ELEC_BUS_SALES_TAX_AMT","Number"],      #매출세금계산서 총합계-전자세금계산서발급분-사업자등록번호 발급분-세액

    ["ELEC_PSN_SALES_CNT","Number"],          #매출세금계산서 총합계-전자세금계산서발급분-주민등록번호 발급분-매출처수
    ["ELEC_PSN_SALES_QTY","Number"],          #매출세금계산서 총합계-전자세금계산서발급분-주민등록번호 발급분-매수
    ["ELEC_PSN_SALES_ACT_AMT","Number"],      #매출세금계산서 총합계-전자세금계산서발급분-주민등록번호 발급분-공급가액
    ["ELEC_PSN_SALES_TAX_AMT","Number"],      #매출세금계산서 총합계-전자세금계산서발급분-주민등록번호 발급분-세액

    ["ELEC_TOT_SALES_CNT","Number"],          #매출세금계산서 총합계-전자세금계산서발급분-소계-매출처수
    ["ELEC_TOT_SALES_QTY","Number"],          #매출세금계산서 총합계-전자세금계산서발급분-소계-매수
    ["ELEC_TOT_SALES_ACT_AMT","Number"],      #매출세금계산서 총합계-전자세금계산서발급분-소계-공급가액
    ["ELEC_TOT_SALES_TAX_AMT","Number"],      #매출세금계산서 총합계-전자세금계산서발급분-소계-세액

    ["NON_ELEC_BUS_SALES_CNT","Number"],      #매출세금계산서 총합계-전자세금계산서외 발급분-사업자등록번호 발급분-매출처수
    ["NON_ELEC_BUS_SALES_QTY","Number"],      #매출세금계산서 총합계-전자세금계산서외 발급분-사업자등록번호 발급분-매수
    ["NON_ELEC_BUS_SALES_ACT_AMT","Number"],  #매출세금계산서 총합계-전자세금계산서외 발급분-사업자등록번호 발급분-공급가액
    ["NON_ELEC_BUS_SALES_TAX_AMT","Number"],  #매출세금계산서 총합계-전자세금계산서외 발급분-사업자등록번호 발급분-세액

    ["NON_ELEC_PSN_SALES_CNT","Number"],      #매출세금계산서 총합계-전자세금계산서외 발급분-주민등록번호 발급분-매출처수
    ["NON_ELEC_PSN_SALES_QTY","Number"],      #매출세금계산서 총합계-전자세금계산서외 발급분-주민등록번호 발급분-매수
    ["NON_ELEC_PSN_SALES_ACT_AMT","Number"],  #매출세금계산서 총합계-전자세금계산서외 발급분-주민등록번호 발급분-공급가액
    ["NON_ELEC_PSN_SALES_TAX_AMT","Number"],  #매출세금계산서 총합계-전자세금계산서외 발급분-주민등록번호 발급분-세액

    ["NON_ELEC_TOT_SALES_CNT","Number"],      #매출세금계산서 총합계-전자세금계산서외 발급분-소계-매출처수
    ["NON_ELEC_TOT_SALES_QTY","Number"],      #매출세금계산서 총합계-전자세금계산서외 발급분-소계-매수
    ["NON_ELEC_TOT_SALES_ACT_AMT","Number"],  #매출세금계산서 총합계-전자세금계산서외 발급분-소계-공급가액
    ["NON_ELEC_TOT_SALES_TAX_AMT","Number"],  #매출세금계산서 총합계-전자세금계산서외 발급분-소계-세액
    [
        ["NON_ELEC_NO","Number"],             #전자세금계산서외 발급분에 대한 매출처별 명세-일련번호
        ["NON_ELEC_BUS_NO","String"],         #전자세금계산서외 발급분에 대한 매출처별 명세-사업자등록번호
        ["NON_ELEC_BUS_NAME","String"],       #전자세금계산서외 발급분에 대한 매출처별 명세-상호(법인명)
        ["NON_ELEC_QTY","Number"],            #전자세금계산서외 발급분에 대한 매출처별 명세-매수
        ["NON_ELEC_ACT_AMT","Number"],        #전자세금계산서외 발급분에 대한 매출처별 명세-공급가액
        ["NON_ELEC_TAX_AMT","Number"],        #전자세금계산서외 발급분에 대한 매출처별 명세-세액
        ["ETC","String"]                      #전자세금계산서외 발급분에 대한 매출처별 명세-비고
    ]

]

# 화면상의 계산 식을 위한 공간 / 자동화 하기 위해 고민이 필요함.
calc = [
["TOTAL_AMOUNT","(CARD_TOTAL_AMOUNT+CASH_TOTAL_AMOUNT-XXX)/YYY*ZZZ"]
]

# MSSQL의 NAV Table DocumentVATEntry 에서 가져올 대상을 지정합니다. (SQL 컬럼명을 지정합니다.)
# V104 (신용카드매출전표등 수령금액 합계표)에서 사용 할 MSSQL 컬럼명을 입력합니다.
Entries = [
"BSE_VAT Category Code",
"BSE_Pay_Bill CorpIndv Type",
"BSE_ETAX Complete issue",
"BSE_Editable Tot Actual Amount",
"BSE_Editable Tot VAT Amount",
"BSE_VAT Registration No_",
"BSE_VAT Name"
]

# NAV 쿼리를위한 조건을 입력합니다.
[[V104.Condition]]
key = "BSE_VAT Type"
value = "1"
value_type = "Integer"

[[V104.Sub]]
key = "BSE_VAT Category Code"
query = "SELECT [BSE_Category Code]
         FROM [#Company$B_VAT Category]
         WHERE [BSE_VAT Total Report] = 1"